// export const HOST = process.env.NEXT_PUBLIC_NODE_BACKEND_URL;

const CONTACTSAPI = `/api/contacts`;
const SEARCHCONTACTSROUTES = `${CONTACTSAPI}/search`;
const GET_DM_CONTACTS_ROUTES = `${CONTACTSAPI}/get-contact-for-dm`;
const GET_ALL_CONTACTS_ROUTES = `${CONTACTSAPI}/get-all-contacts`;

const MESSAGESAPI = `/api/messages`;
const GETALLMESSAGESROUTES = `${MESSAGESAPI}/get-messages`;
const UPLOAD_FILE_ROUTE = `${MESSAGESAPI}/upload-file`;

const CHANNEL_ROUTES = `/api/channel`;
const CREATE_CHANNEL_ROUTE = `${CHANNEL_ROUTES}/create-channel`;
const GET_USER_CHANNEL_ROUTE = `${CHANNEL_ROUTES}/get-user-channels`;

export {
  SEARCHCONTACTSROUTES,
  GETALLMESSAGESROUTES,
  GET_DM_CONTACTS_ROUTES,
  UPLOAD_FILE_ROUTE,
  GET_ALL_CONTACTS_ROUTES,
  CREATE_CHANNEL_ROUTE,
  GET_USER_CHANNEL_ROUTE,
};
