import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/common/providers";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { useEffect } from "react";
import ClientProviders from "@/lib/client-providers";
import { SocketProvider } from "@/context/socket-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <SocketProvider>
              {/* <ClientProviders> */}
              {children}
              <Toaster closeButton />
              {/* </ClientProviders> */}
            </SocketProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
